### ISSUE TITLE
Service stuck on "activating" 

### ISSUE THREAD

**Issue by jo-me** [timolex/Radiodawg#1]
Hi,
thanks for sharing this script.

I had problems getting it to run as systemd service.
It was stuck on "activating" and never printed any logs.

Had more luck with this service description:

```
[Unit]
Description=run radiodawg Python script at startup
After=network.target
After=syslog.target

[Service]
Type=simple
User=root
ExecStart=/usr/bin/python3 -u /usr/bin/radiodawg.py

[Install]
WantedBy=multi-user.target

```

notice the "-u" parameter in ExecStart for unbuffered output. Without it I could not see any logs in "systemctl status .." .
Maybe all the flushes in the python script become obsolete with this change.

Cheers

**Comment by timolex** [comment]
@jo-me Thanks a lot for all your valuable feedback! To be honest, being a systemd-newbie, radiodawg.service has so far just been a "quick and dirty" solution for getting things to work on my system. The linked PR addresses almost all of your suggestions, but I prefer to stick with python (Python 2.7), since the plain-vanilla Volumio OS for RPi doesn't come with python3.
